s3cfb: fix compilation error
It's strange it was not reported/fixed earlier.
Compilation error is:
===
drivers/video/fbmem.c:39:27: fatal error: samsung/s3cfb.h: No such file or directory
===

Obviously this is because "drivers/video" are not added in include paths with "-I"
So this is fixed by changing header inclusion from <> to "" so now we're pointing compiler to look for header starting from current locatoin.

This issue could be fixed by inclusion of "drivers/video" to include paths in "drivers/video/Makefile" but since this path is needed by only 1 file "fbmem.c" there's no point in changing other generic files.

Change-Id: I438b9913cc2b3270fc1703d751107ff4378906d7